# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from recognize import Recognizer
from encryption import Encryptor
from program import *

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 120, 81, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.cornfirmPassword)
        
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 120, 241, 41))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 90, 241, 21))
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Cornfirm"))
        self.label.setText(_translate("MainWindow", "Input Password to continue:"))
    def cornfirmPassword(self):
        a =self.textEdit.text()
        passw = '2122000'
        print(a)
        if a == passw:
            key = b'[EX\xc8\xd5\xbfI{\xa2$\x05(\xd5\x18\xbf\xc0\x85)\x10nc\x94\x02)j\xdf\xcb\xc4\x94\x9d(\x9e'
            enc = Encryptor(key)
            enc.decrypt_file("./pickle/label.pickle.enc")
            enc.decrypt_file("./pickle/classifier.pickle.enc")
            recog = Recognizer()
            detection = recog.recognize()
            enc.encrypt_file("./pickle/label.pickle")
            enc.encrypt_file("./pickle/classifier.pickle")
            if(not detection):
                msgBox= QtWidgets.QMessageBox()
                msgBox.setIcon(QtWidgets.QMessageBox.Critical)
                msgBox.setText("người dùng không tin cậy!")
                msgBox.exec()
            else:
                print('ok rồi đấy!')
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow_program()
                self.ui.setupUi_program(self.window)
                self.window.show()
                MainWindow.hide()
            # os.system('python program.py')
        else :
            msgBox= QtWidgets.QMessageBox()
            msgBox.setIcon(QtWidgets.QMessageBox.Critical)
            msgBox.setText("wrong password!")
            msgBox.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
